### ISSUE TITLE
Plugin has dependency to pxsdk  

### ISSUE THREAD

**Issue by TubsDK** [praxisdigital/mod_smartlink#17]
The version manifest does not declare any dependencies but the plugin throws the following 

`Exception - Class "local_pxsdk\app\v7\moodle\factory" not found
` 
Since this is open sourced there should not be any dependencies to closed source code.

**Comment by AraPraxis** [comment]
## Changes
- Removed pxsdk dependency

## Test
- The plugins works as expected

## Info
Branch: ara_GH-17_42
PR: https://github.com/praxisdigital/mod_smartlink/pull/18
Moodle: 4.2

**Comment by AraPraxis** [comment]
## Release

New version: 2024042900
Moodle: 4.2+
